### ISSUE TITLE
Time is shown in weird numbers

### ISSUE THREAD

**Issue by kingisch** [haidarn2/Youtube15#2]
Hi

i have just recently started to use the Youtube15 applet with my G15. It works but the time shown on the display looks kind of weird (see picture attached).

Any ideas what is wrong?

Thanks in advance
![k640_2017-05-27 11 39 08](https://cloud.githubusercontent.com/assets/28997130/26520399/1f1b6ed6-42d2-11e7-995c-07bb07aae186.JPG)

**Comment by haidarn2** [comment]
Hi, this issue is likely related to a bug with the decimal parser that I fixed in January but haven't released yet.

Can you test the pre-release of V1.3 and let me know if it works?
https://github.com/haidarn2/Youtube15/files/728387/YouTube15_v1.3_prerelease.zip
Thanks!

**Comment by kingisch** [comment]
Nice, this was easy - it worked!

**Comment by haidarn2** [comment]
Glad to hear it worked!

The issue was because v1.2 doesn't know how to handle comma decimal marks for the video time values. eg `50.10` seconds vs `50,10` seconds. I added support for international decimal marks in January but forgot to make a new release; I'll do this now.

Thanks again for testing it!
